### ISSUE TITLE
Implement Auth and Groups

### ISSUE THREAD

**Issue by gcarvellas** [castlepointanime/backend#3]
This needs to be split into other issues

# List of Features to Implement

## Auth

- Implement auth. We need to discuss what auth we're going to use.

## Implement groups, roles, and permissions. Make permissions as needed.

- Groups: User, Staff
- Roles: Admin

### User Features

- signup (with email vertification)
- login
- logout
- create artist OR dealer form
- view user's own contract (note: a user can only make 1 contract)

### Staff Features

- can see all pending contracts

**Comment by KevinHa48** [comment]
We will be going forward with Cognito

**Comment by gcarvellas** [comment]
AWS Cognito does not have roles, so we're going with these groups:

```
Artist
Dealer
Staff
Admin
```

**Comment by KevinHa48** [comment]
test

**Comment by gcarvellas** [comment]
This issue will also cover the /me routes for both admin and user
